version: "3.8"

services:
  comfyui:
    image: charlesc234/comfyui:v1.0.0
    container_name: comfyui-worker
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - SERVE_API_LOCALLY=true
    ports:
      - "8000:8000"
    runtime: nvidia
    volumes:
      - ./data/comfyui/output:/comfyui/output
